// <auto-generated />
using System;
using Member.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Member.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200714142046_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Member.Data.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemberFK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.HasIndex("MemberFK");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Member.Data.Psa", b =>
                {
                    b.Property<int>("PsaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArbeitsHose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArbeitsJacke")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EinsatzHose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EinsatzJacke")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Handschuhe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Helm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HelmDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kopfschutzhaube")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Schuhe")
                        .HasColumnType("INTEGER");

                    b.HasKey("PsaId");

                    b.ToTable("Psa");
                });

            modelBuilder.Entity("Member.Data.Member", b =>
                {
                    b.HasOne("Member.Data.Psa", "Psa")
                        .WithMany()
                        .HasForeignKey("MemberFK");
                });
#pragma warning restore 612, 618
        }
    }
}
